TrajectoryPlannerROS:

  holonomic_robot: false
  max_vel_x: 1.2
  min_vel_x: 0.1
  max_vel_theta: 4.0
  min_vel_theta: -4.0
  min_in_place_vel_theta: 0.4
  acc_lim_theta: 2.0
  acc_lim_x: 1.2
  acc_lim_y: 1.2  
  escape_vel: -0.1
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.02
  sim_time: 1.0
  meter_scoring: true
  pdist_scale: 1.0
  vx_samples: 5
  vtheta_samples: 10