odom_frame_id: odom
base_frame_id: robot_footprint
global_frame_id: map

#acml params
initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: -0.5
min_particles: 10
max_particles: 50
transform_tolerance: 0.3

#laser
laser_model_type: likelihood_field
laser_likelihood_max_dist: 3.0
laser_z_hit: 0.95
laser_z_rand: 0.05

#odom
odom_model_type: "diff-corrected"
odom_alpha1: 0.005
odom_alpha2: 0.005
odom_alpha3: 0.010
odom_alpha4: 0.005
odom_alpha5: 0.003
